name: Pipeline

on: [push]

env:
    PYTHONPATH: ${{ github.workspace }}/src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --user pipx
        python3 -m pipx ensurepath
        pipx install poetry
        poetry install
    - name: Analysing the code with pylint
      run: |
        poetry run pylint src
    - name: Running unit tests
      run: |
        poetry run pytest --cov=src --cov-branch --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        files: coverage.xml
        verbose: true
    - name: Running robot tests
      run: |
        poetry run robot src/tests
